spring:
  profiles:
    active: dev
  application:
    name: provider
---
server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: v1
  profiles: dev


