spring:
  profiles:
    active: prod
  application:
    name: provider
---

server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        metadata:
          version: v2
  profiles: prod


